name: IPFS Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        env:
          VITE_INFURA_API_KEY: ${{ vars.INFURA_API_KEY }}
        run: |
          yarn
          yarn build

      - name: IPFS (Infura)
        uses: aquiladev/ipfs-action@master
        with:
          path: ./dist
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: IPFS (Pinata)
        uses: aquiladev/ipfs-action@master
        with:
          path: ./dist
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}